@WinLimitAPI_HostAddress = https://localhost:7266

POST {{WinLimitAPI_HostAddress}}/api/blockitem
Content-Type: application/json

{
    "friendlyName":"Notepad",
    "executableName":"notepad",
    "description": "Notepad application, test reason"
}

###
GET {{WinLimitAPI_HostAddress}}/api/blockitem
Content-Type: application/json
